apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: openshift-image-registry
data:
  config.yml: |
    version: 0.1
    log:
      level: info
      formatter: text
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
      http2:
        disabled: false
      # Increase timeouts for large images and CI workloads
      readtimeout: 300s
      writetimeout: 300s  
      idletimeout: 300s
      # Increase max header size for large manifests
      maxheadersize: 16384
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
      cache:
        blobdescriptor: inmemory
      maintenance:
        uploadpurging:
          enabled: true
          age: 168h
          interval: 24h
          dryrun: false
    # Performance tuning for CI workloads  
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3 